FROM nginx:1.27-alpine

COPY index.html dashboard.html login.html usuarios.html maquinas.html historico.html /usr/share/nginx/html/
COPY css/ /usr/share/nginx/html/css/
COPY js/ /usr/share/nginx/html/js/

EXPOSE 80