-- Gerado por `python -m app.scripts.exportar_catalogos`.
-- Aplique com `seed_db.py` apontando SEEDS_FILE para este arquivo.

INSERT INTO maquinas (numero_maquina, descricao, cavidades, ciclo_padrao, ativo) VALUES
('1', 'Injetora 01 - Peça A', 4, 18.5, true),
('2', 'Injetora 02 - Peça B', 2, 22.0, true),
('3', 'Injetora 03 - Peça C', 8, 15.0, false),
('4', 'Injetora 04 - Peça D', 4, 20.0, false),
('5', 'Injetora 05 - Peça E', 1, 30.0, false),
('6', 'Injetora 06 - Peça F', 6, 16.5, false),
('7', 'Injetora 07 - Peça G', 2, 20.0, false)
ON CONFLICT (numero_maquina) DO NOTHING;

INSERT INTO produtos (codigo, descricao, ciclo_padrao, cavidades, peso_gramas, ativo) VALUES
('1', 'Tube Alimentation 1/2', 45.0, NULL, NULL, true),
('1.1', 'Tube Alimentation 3/8', 46.0, NULL, NULL, true),
('10', 'Flotteur 755', 36.0, NULL, NULL, true),
('10.1', 'Flotteur 754 (bran)', 36.0, NULL, NULL, true),
('10.2', 'Flotteur 754 (lar)', 36.0, NULL, NULL, true),
('10.3', 'Flotteur 755 (Orange 152C)', 36.0, NULL, NULL, true),
('10D', 'Flotteur 755 (Blue)', 36.0, NULL, NULL, true),
('10L', 'Flotteur 755 Liso', 36.0, NULL, NULL, true),
('11', 'Corps Etrangleur', 25.0, NULL, NULL, true),
('11D', 'Corps Etrangleur (Gray)', 25.0, NULL, NULL, true),
('12', 'Plaquette Etrier', 24.0, NULL, NULL, true),
('12D', 'Plaquette Etrier (Gray)', 24.0, NULL, NULL, true),
('13', 'Bras Actionament', 21.0, NULL, NULL, true),
('13D', 'Bras Act. (Gray)', 21.0, NULL, NULL, true),
('14', 'Clip Blocage 780', 15.0, NULL, NULL, true),
('15', 'Clip Blocage 755', 15.0, NULL, NULL, true),
('15D', 'Clip Blocage 755 (Blue)', 15.0, NULL, NULL, true),
('16', 'Interieur Etran. (cinz)', 38.0, NULL, NULL, true),
('16D', 'Interieur Etran. (Blue)', 38.0, NULL, NULL, true),
('17', 'Bouchon 755', 23.0, NULL, NULL, true),
('17D', 'Bouchon 755 (Gray)', 23.0, NULL, NULL, true),
('18', 'Tige Commande', 18.0, NULL, NULL, true),
('18D', 'Tige Commande (Gray)', 18.0, NULL, NULL, true),
('19', 'Curseur Excentration', 25.0, NULL, NULL, true),
('19D', 'Curseur Exc. (Gray)', 25.0, NULL, NULL, true),
('1D', 'Tube Alim. 1/2 (Gray)', 45.0, NULL, NULL, true),
('2', 'Bonde Brio', 46.0, NULL, NULL, true),
('2.1', 'Bonde Brio NPSM', 46.0, NULL, NULL, true),
('20', 'Tirette Poussoir', 17.0, NULL, NULL, true),
('20D', 'Tirette Poussoir (Blue)', 17.0, NULL, NULL, true),
('21', 'Bras Hydraulique', 22.0, NULL, NULL, true),
('21.1', 'Bras Hydraulique Neutro', 22.0, NULL, NULL, true),
('21.2', 'Bras Hydraulique NF', 22.0, NULL, NULL, true),
('21D', 'Bras Hydraulique (Blue)', 22.0, NULL, NULL, true),
('22', 'Clip Tube', 19.0, NULL, NULL, true),
('22D', 'Clip Tube (Blue)', 19.0, NULL, NULL, true),
('23', 'Capot', 57.0, NULL, NULL, true),
('23D', 'Capot (Gray)', 57.0, NULL, NULL, true),
('24', 'Base Porte Clapet', 44.0, NULL, NULL, true),
('24D', 'Base Porte Clapet (Gray)', 44.0, NULL, NULL, true),
('25', 'Ecrou de Tete', 23.0, NULL, NULL, true),
('25D', 'Ecrou de Tete (Gray)', 23.0, NULL, NULL, true),
('26', 'Vis Exter Boite', 27.0, NULL, NULL, true),
('26D', 'Vis Exter Boite (Blue)', 27.0, NULL, NULL, true),
('27', 'Vis de Reglage 755', 22.0, NULL, NULL, true),
('27.1', 'Vis de Reglage 780', 21.0, NULL, NULL, true),
('27D', 'Vis de Reg. 755 (Blue)', 22.0, NULL, NULL, true),
('28', 'Support Vis Exter', 24.0, NULL, NULL, true),
('28D', 'Support Vis Ex. (Gray)', 24.0, NULL, NULL, true),
('29', 'Accroche Tirrete C', 26.0, NULL, NULL, true),
('29.1', 'Accroche Tirrete L', 26.0, NULL, NULL, true),
('29.2', 'Accr. Tirrete L 10 Crans', 26.0, NULL, NULL, true),
('29.2D', 'Accr. Tirrete L (Gray) 10 Crans', 26.0, NULL, NULL, true),
('29.3', 'Accr. Tirrete L 8 Crans', 26.0, NULL, NULL, true),
('29D', 'Accr. Tirrete C (Gray)', 26.0, NULL, NULL, true),
('2D', 'Bonde Brio (Gray)', 46.0, NULL, NULL, true),
('2D.1', 'Bonde Brio (Gray) NPSM', 46.0, NULL, NULL, true),
('3', 'Tube Remplissage', 25.0, NULL, NULL, true),
('30', 'Filtre Reducteur', 23.0, NULL, NULL, true),
('31', 'Curseur Residuel', 25.0, NULL, NULL, true),
('31D', 'Curseur Residuel (Blue)', 25.0, NULL, NULL, true),
('32', 'Guide Flotteur', 31.0, NULL, NULL, true),
('32D', 'Guide Flotteur (Blue)', 31.0, NULL, NULL, true),
('33', 'Flotteur DV', 27.0, NULL, NULL, true),
('34', 'Flotteur PV', 41.0, NULL, NULL, true),
('34D', 'Flotteur PV (Blue)', 41.0, NULL, NULL, true),
('35', 'Rondelle Anti-voilage', 26.0, NULL, NULL, true),
('36', 'Capot DV PS/ABS', NULL, NULL, NULL, true),
('37', 'Bonde Brio (Gray) NIKITA', NULL, NULL, NULL, true),
('38', 'Bascule DV', 40.0, NULL, NULL, true),
('39', 'Suporte (Cartucho)', NULL, NULL, NULL, true),
('3D', 'Tube Remplissage (Gray)', 25.0, NULL, NULL, true),
('4', 'Bonde Flap Brio', 45.0, NULL, NULL, true),
('4.1', 'Bonde Flap Brio Mod', 44.0, NULL, NULL, true),
('4.1D', 'Bonde Flap Brio Mod (Gray)', 44.0, NULL, NULL, true),
('40', 'Tampa (Cartucho)', NULL, NULL, NULL, true),
('41', 'Reservatorio (Cartucho)', NULL, NULL, NULL, true),
('42', 'Ecrou de Boitier', 28.0, NULL, NULL, true),
('43', 'Tige Bouton', 16.0, NULL, NULL, true),
('44', 'Porte Bras Flap Brio', 21.0, NULL, NULL, true),
('45', 'Chapeau Flap Brio', 24.0, NULL, NULL, true),
('45D', 'Chapeau Flap Brio (Blue)', 24.0, NULL, NULL, true),
('46', 'Bras Flap Brio', 28.0, NULL, NULL, true),
('47', 'Flotteur Flap Brio', 24.0, NULL, NULL, true),
('48', 'Parafuso Vis M10', 52.0, NULL, NULL, true),
('49', 'Ecrou de Bonde', 32.0, NULL, NULL, true),
('49.1', 'Ecrou de Bonde NPSM', 32.0, NULL, NULL, true),
('4D', 'Bonde Flap Brio (Gray)', 45.0, NULL, NULL, true),
('5', 'Etrier', 29.0, NULL, NULL, true),
('5.1', 'Etrier NF', 29.0, NULL, NULL, true),
('5.2', 'Etrier Neutre', 29.0, NULL, NULL, true),
('5D', 'Etrier (Gray)', 29.0, NULL, NULL, true),
('6', 'Tube Surverse Brio', 24.0, NULL, NULL, true),
('6.1', 'Tube Surverse Flap', 24.0, NULL, NULL, true),
('6.1D', 'Tube Sur. Flap (Gray)', 24.0, NULL, NULL, true),
('6.2', 'Tube Surverse Int.', 23.0, NULL, NULL, true),
('6D', 'Tube Sur. Brio (Gray)', 24.0, NULL, NULL, true),
('7', 'Corps Bas', 43.0, NULL, NULL, true),
('8', 'Flotteur 780', 32.0, NULL, NULL, true),
('9', 'Boite 755', 32.0, NULL, NULL, true),
('9.1', 'Boite 755 (Orange 152C)', 32.0, NULL, NULL, true),
('9D', 'Boite 755 (Blue)', 32.0, NULL, NULL, true)
ON CONFLICT (codigo) DO NOTHING;
